parameters:
    stock.email.sender: '%env(STOCK_NOTIFICATION_SENDER)%'
    stock.email.receiver: '%env(STOCK_NOTIFICATION_RECEIVER)%'
    stock.public_path: '%env(STOCK_PUBLIC_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Repository
    maranqz\StockBundle\Repository\StockRepository: ~

    # Controller
    maranqz\StockBundle\Controller\StockController: ~

    # Service
    maranqz\StockBundle\Service\StockService: ~

    # Event Dispatcher
    maranqz\StockBundle\EventListener\StockChangeListener:
        tags:
            - { name: kernel.event_subscriber }
    maranqz\StockBundle\Component\EventDispatcher\DelayedEventDispatcher:
        decorates: Symfony\Component\EventDispatcher\EventDispatcherInterface

    # Message
    maranqz\StockBundle\MessageHandler\StockOutNotificationHandler:
        arguments:
            $notificationSender: '%stock.email.sender%'
            $notificationReceiver: '%stock.email.receiver%'
        tags: [ messenger.message_handler ]

    # Command
    maranqz\StockBundle\Command\StockImportCommand:
        arguments:
            $publicPath: '%stock.public_path%'